if has("nvim")
    " If you unset this you get the default background but none of the rest of
    " the theme
    set termguicolors
    set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
elseif has("gui")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_win32")
        set guifont=Consolas:h10:cANSI
    endif
endif

execute pathogen#infect('bundle/{}', '~/.config/nvim/bundle/{}')
call plug#begin('~/.vim/plugged')
Plug 'hzchirs/vim-material'

" Dark
set background=dark
colorscheme vim-material

" This works on the modeline :-/
"hi Normal guibg=NONE
"hi Normal ctermbg=NONE
" The actual colour set by material theme is
"hi Normal ctermbg=#263238

syntax on
set nolist
set expandtab ts=4 sw=4 ai

set number
set norelativenumber

" Annoying highlighting of 'tabs'
let g:indent_guides_auto_colors = 0
" https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

" Some files need syntax setting
" NANT (like I need that)
au BufRead,BufNewFile *.build set filetype=xml
" .aliases obvs
au BufRead,BufNewFile *.aliases set filetype=sh

" Pretty pointless
:let g:netrw_dirhistmax = 0
