disable = [ 
    "containers",
    "github_cli_extensions",
    "vim",
    "gem",
    "node",
#    "go",
    "node",
    "opam",
    "gcloud",
    "dotnet",
#    "vscode",
#    "vscodium",
    "gnome_shell_extensions",
    "vagrant"
]

assume_yes = true

no_retry = true

cleanup = true

[git]
repos = []

