disable = [ 
    "vim",
    "gem",
    "node",
#    "go",
    "node",
    "opam",
    "gcloud",
    "dotnet"
#    "vscode",
#    "vscodium"
]

assume_yes = true

no_retry = true

cleanup = true

[git]
repos = []

